<?php

/**
 * Implements hook_form_alter().
 */
function tecnomagneti_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form['#form_id'] == 'search_block_form') {
    if (!empty($_GET['keys'])) {
      $form['keys']['#default_value'] = $_GET['keys'];
    }
  }
}

/**
 * Implements hook_mail().
 */
function tecnomagneti_mail($key, &$message, $params) {
  switch($key) {
    case 'notice':
      $message['subject'] = t('Message from tecnomagneti.ro');
      $message['body'][] = t("Ati primit un mesaj de pe tecnomagneti.ro\n\n");
      $message['body'][] = t("Nume: {$params['name']}\n");
      $message['body'][] = t("E-mail: {$params['mail']}\n");
      $message['body'][] = t("Mesaj: {$params['message']}\n");
      break;
  }
}